FROM golang:1.25-rc-bookworm

# Install git (for go get) and curl (optional for debug), and air
# RUN apk add --no-cache git curl 
# && \
    # go install github.com/air-verse/air@latest

WORKDIR /halo

# Copy go.mod/go.sum first for layer caching
COPY go.mod go.sum ./
RUN go mod download

# Copy everything else
COPY . .

# Default command
CMD ["go", "run", "./cmd/main.go"]
